[trace.jaeger]
[cron.test]
spec = "*/3 * * * * *"
enableDistributedTask = false          # 是否分布式任务，默认否，如果存在分布式任务，会只执行该定时人物
enableImmediatelyRun = false        # 是否立刻执行，默认否
enableSeconds = true      # 是否使用秒作解析器，默认否
delayExecType = "skip"  # skip，queue，concurrent，如果上一个任务执行较慢，到达了新任务执行时间，那么新任务选择跳过，排队，并发执行的策略，新任务默认选择skip策略
